### PR TITLE
ember-cli 2016-03-17

### PR DESCRIPTION
**Pull request by nathanhammond**
/cc @trabus @stefanpenner @kellyselden

Will be merged when I remember to do so on about 3/19. Attendees: add a reaction of "thumbs up" if you feel like these notes are accurate.

### CODE REVIEW

**Comment by mixonic** [comment]
@nathanhammond just to check- you are CC'ing attendees, but we should feel free to merge this? Or you would like people to wait on merge?

**Comment by nathanhammond** [comment]
@mixonic I have privs to this repo and can merge. :) I'm doing this primarily so attendees have an opportunity to correct the minutes before I merge them. I do an editing-for-clarity pass after the meeting which changes the notes taken during the meeting so I want to make sure I don't misconstrue anything before it becomes part of the official record.

I generally try to remember to merge a day or three after the meeting.

**Comment by mixonic** [comment]
I'll leave them to you then :+1: though I might suggest adding the intended date-of-merge, even roughly, to the description so others reading know what the hold is.

Thanks for the continued efforts on this!

**Comment by pangratz** [comment]
How about creating a checkbox for each attendee and everyone checks off hers/his? Of course this only works if every attendee has write access to this repo...

**Comment by nathanhammond** [comment]
@pangratz I like that, but not every attendee will have privs. I'll just add a default note for using reactions with a two day timeline for landing by assent. :)

**Pull request merged**
