### PR TITLE
generate an online book-like website from the notes

### PR DESCRIPTION
**Pull request by hakilebara**
This is an attempt at building a static gitbook like version of the notes. It aims at doing something similar to Ember RFC's website https://emberjs.github.io/rfcs/

Here is a demo of the end result: http://ember-core-notes-demo.surge.sh/

If we are ok with this, can we create a travis build to deploy it on github pages?

### CODE REVIEW

**Comment by mansona** [comment]
Hey @hakilebara thanks for the PR 🎉 

I'm trying to find the conversation that we had about this on Slack but I think it's fallen off the edge of history so I will try to remember it properly. If I remember correctly it was in the #-team-learning channel.

My first reaction to adding something like this is that we are in the process of building a lot of infrastructure in the [ember-learn](https://github.com/ember-learn) subteam that is making use of Markdown to JSON:API parsers so that we can create Ember apps for various websites we're maintaining. I seem to remember you mentioning that it would be overkill but one thing that is a real "killer feature" of this approach is that we can make use of the new [ember-styleguide](https://github.com/ember-learn/ember-styleguide) to make the site follow our current design guidelines, and also keep up to date as those guidelines evolve.

I'm happy to point you in the right direction if you would like a bit of guidance, but in the meantime, you can take a look at how the new [guides-app](https://github.com/ember-learn/guides-app) or the [deprecation-app](https://github.com/ember-learn/deprecation-app) is built.

**Comment by MelSumner** [comment]
@hakilebara this is useful, thank you for it! A couple of questions: 

- how would it stay updated? 
- how do you imagine it fitting into the website?

**Comment by hakilebara** [comment]
The site would be updated by travis builds deploying to github pages either manually or automatically after a PR merge.

Regarding the website integration, I was happy having a separate site living on its own for the time being, just like the RFC site. 

I saw this PR as a quick and easy way to make the notes more readable. I did think that using an ember app for this would be over-engineered. However, if the plan is to integrate the core notes (and the RFCs ?) into the ember website then OK let's do it :)

**Comment by MelSumner** [comment]
We could at least link to them, yeah? :) I really appreciate that you took action here. :+1: :+1: :+1:

**Comment by acorncom** [comment]
Thanks a bunch @hakilebara, this looks great. I’m firmly in favor of merging this and linking to it in someway with the possibility of improving it and potentially integrating it into the main Ember website over time. 

Right now, we’re working on ember-ifying the main website. When that is done, the contents here would seem to fit very nicely in under each individual team’s page to help folks see what is being dealt with by each team.

**Comment by hakilebara** [comment]
Hi, I think this PR is stale now and should be closed. WDYT?

**Comment by MelSumner** [comment]
Closing as a stale issue/pr.

**Pull request closed without merging**
