### PR TITLE
March 3 docs team minutes

### PR DESCRIPTION
**Pull request by toddjordan**

### CODE REVIEW

**Comment by locks** [comment]
@homu r+

**Comment by wifelette** [comment]
@toddjordan Can you rename the 3/3 file so it's consistent with all the tidy work @trentmwillis [just did here](https://github.com/emberjs/core-notes/pull/50)?

**Comment by toddjordan** [comment]
Done I think.  Is this what you had in mind?

**Comment by rwjblue** [comment]
Thanks!

**Pull request merged**
